## tab1 table definition
---
name: tab1
primarykey: id
engine: InnoDB
charset: utf8
autoincrement:
    colname: id
    start: 4
cols:
    id:
        type: bigint
        length: 20
        params: NOT NULL
    text:
        type: varchar
        length: 32
        params: NOT NULL
indices:
defaultvalues:
    rows:
        1:
            id: 1
            text: "Unit test module table 1.1"
        2:
            id: 2
            text: "Unit test module table 1.2"
        3:
            id: 3
            text: "Unit test module table 1.3"